# ms-api-gateway/src/main/resources/application.yml
server:
  port: 8080

spring:
  application:
    name: ms-api-gateway
  cloud:
    gateway:
      routes:
        - id: ms-auth
          uri: lb://ms-auth
          predicates:
            - Path=/api/auth/**, /api/users/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}
        - id: ms-expense
          uri: lb://ms-expense
          predicates:
            - Path=/api/expenses/**, /api/categories/**
          filters:
            - RewritePath=/api/(?<segment>.*), /api/$\{segment}

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty: DEBUG